name: fauxturf
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: 4.6.5
  google_fonts: ^3.0.1
  iconify_flutter: ^0.0.4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  lints: 2.0.0

flutter:
  uses-material-design: true
  assets:
    - asset/image/
